### PR TITLE
Umlaut4

### PR DESCRIPTION
**Pull request by scotdalton**
Update for Umlaut 4.x

### CODE REVIEW

**Comment by jrochkind** [comment]
Awesome. 

I hadn't meant to change anything that would be relevant to bccf057, but I guess I did? Is it a problem?

I don't really understand this code, but do you want me to hit 'merge' for you, or do you want to do it?

**Comment by scotdalton** [comment]
I'll go ahead and merge, I'm just waiting on Travis. Sorry, I'm just getting around to upgrading.

**Comment by jrochkind** [comment]
Ha, it usually takes me way longer than a month or two to get around to upgrades like this.

**Comment by scotdalton** [comment]
Just to test.

**Pull request merged**
